
```{r}
require(RNeXML)
```

A helper function to avoid empty / non-XML filles in supertreebase records
```{r}
files <- system("ls ~/Documents/data/supertreebase/data/treebase/*.xml", intern=TRUE)
parses <- sapply(files, function(x){
                out <- try(xmlParse(x))
                if(is(out, "try-error"))
                  out <- x
                else {
                  free(out)
                  out = "success"
                }
                out
                })
fails <- parses[parses!="success"]
works <- files[parses == "success"]
```


Define a function to compute the metadata of interest

```{r}
## Easiest with xpath expressions 
get_tree_meta <- function(nexml){
  c(ntaxa = length(nexml@otus@otu)
  authors =  
  pubdate = 
  rights = 
  title = 
  publisher = 
  id = 
  has_branchlengths = )
}
```

Loop over the data applying the extraction function.  
```{r} 
treebase <- sapply(works, 
                function(x){
                  message(x)
                  tree <- try(nexml_read(x, "nexml"))
                  out <- get_tree_meta(tree)
                  rm(tree)
                  out
                })
```
