
# Copy the markdown version as the README
# This README is for automated use by R package manager only.  
# Run Rscript -e 'knitr::knit("tutorial.Rmd")' from this dir to build tutorial.md first

../README.md: tutorial.md
	cp tutorial.md ../README.md
