
#setMethod("head", signature("nexml"), function(x, n=6L, ...){
#          write.nexml(x, "tmp123.xml")
#          txt <- readLines("tmp123.xml", n=n)
#          unlink("tmp123.xml")
#          cat(txt, "\n")
#})
#setMethod("tail", signature("nexml"), function(x, n=6L, ...){
#          write.nexml(x, "tmp123.xml")
#          txt <- readLines("tmp123.xml", n=-n)
#          unlink("tmp123.xml")
#          cat(txt, "\n")
#})
setMethod("show", signature("nexml"), function(object){
          summary(object)
})



setMethod("summary", signature("nexml"), function(object){
          doc <- xmlParse(write.nexml(object))
          nmeta <- length(getNodeSet(doc, "//x:meta", namespaces="x"))
          ntrees <- length(getNodeSet(doc, "//x:tree", namespaces="x"))
          ncharacters <- length(getNodeSet(doc, "//x:characters", namespaces="x"))
          notu <- length(getNodeSet(doc, "//x:otu", namespaces="x"))

          cat(paste("A nexml object representing:\n",
              "\t", ntrees, "phylogenetic trees", "\n",
              "\t", nmeta, "meta elements", "\n",
              "\t", ncharacters, "character matrices", "\n",
              "\t", notu, "taxonomic units", "\n",
              "Taxa: \t", paste(head(get_taxa(object)), collapse = ", "), "...", "\n\n",
              "NeXML generated by", object@generator, "using",
              "schema version:", object@version, "\n", 
              "size:", capture.output(print(object.size(object), units="auto")), "\n"))

})

